// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcojeziuzrcsvjgknvnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jb2pleml1enJjc3ZqZ2tudm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjI0OTcsImV4cCI6MjA2NDQ5ODQ5N30.TjaQyODt5__2WeKyYaQVi9RmkSZ2JvCT1Bjmzseq5PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);